- arch/x86/realmode/rm/trampoline_64.S
Fix the Secure Launch AP entry point to use the proper 32b addresses
for setting trampoline_status and loading the real mode stack.
> [revision] for {070a29e0ada556e07e6754132dc9ae85ef72bb8e}

- arch/x86/boot/compressed/sl_stub.S
x86: Fix TXT post-launch order of enabling SMI, starting APs etc.
To be more consistent with the TXT specification, reorder several
operations in the early TXT post-launch.
BSP: enable SMI/NMI, wake APs then restory MTRRs
APs: restore MTRRs, enable SMI/NMI
Signed-off-by: Eric Snowberg <eric.snowberg@oracle.com>
Tested-by: Ross Philipson <ross.philipson@oracle.com>
> [revision] for {3d9bbfb1600befd8aa57a73c6c15affd78e11cd8}

- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/asm-offsets.c
- arch/x86/kernel/setup.c
- arch/x86/kernel/slaunch.c
- arch/x86/kernel/smpboot.c
- arch/x86/realmode/rm/trampoline_64.S
- drivers/iommu/dmar.c
- include/linux/slaunch.h
Since the slaunch.h file is not used outside of arch/x86 it has to move to include/linux. Also reduce the number of ifdefs for Secure Launch in the code by using stub definitions for functions.
> Move Secure Launch header and remove ifdefs

- Documentation/x86/boot.rst
- arch/x86/boot/Makefile
- arch/x86/boot/compressed/Makefile
- arch/x86/boot/compressed/kaslr.c
- arch/x86/boot/compressed/kernel_info.S
- arch/x86/boot/header.S
- arch/x86/boot/tools/build.c
- arch/x86/include/uapi/asm/bootparam.h
- arch/x86/kernel/e820.c
- arch/x86/kernel/kdebugfs.c
- arch/x86/kernel/ksysfs.c
- arch/x86/kernel/setup.c
- arch/x86/mm/ioremap.c
- include/linux/slaunch.h
This PR brings in Daniel Kiper's kernel_info patches without conflict and switches Secure Launch to use kernel_info to find the mle_header offset.
> Switch to kernel_info for locating the MLE header

- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/asm-offsets.c
- arch/x86/kernel/slaunch.c
- arch/x86/kernel/smpboot.c
- include/linux/slaunch.h
This scratch space is used to:
- Hold the %ebp base pointer for use on APs at startup.
- Hold the jmp offset in the relocated AP wake block used in SMP startup.
> Create an MLE scratch area in the heap for MLE use

- arch/x86/boot/compressed/early_sha256.c
- arch/x86/boot/compressed/sl_main.c
- arch/x86/realmode/rm/trampoline_64.S
- The trampoline_status field disappeared from the rmpiggy code in 5.4
- The sha256 files moved around
What ever caused sha256 files to move around should be imitated when we add the sha512 files.
> Fix migration issues

- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
This one should be straight forward - it is just changing the names of some definitions.
> Cleanup of main SL header from v2 internal review

- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/boot/compressed/vmlinux.lds.S
Numerous changes from internal code review v2:
- Use readq/writeq for TXT register IO.
- Use hlt instead of pause where possible.
- Introduce GETSEC macro.
- Do not assume AMD during CPU identification.
- Rename some symbols for clarity.
- Add ASSERT in linker script that wake block code <= PAGE_SIZE.
> Numerous changes from internal code review v2

- arch/x86/boot/compressed/early_tpm.c
Remove release locality loop from tis_init()
This loop was causing crashes on the Neon City platform and is not
needed in the end anyway.
> TPM locality loop

- arch/x86/boot/compressed/kernel_info.S
Add ifdef CONFIG_SECURE_LAUNCH to kernel_info
This was unfortunately discovered after the RFC went out and it
prevents building w/ CONFIG_SECURE_LAUNCH disabled.
> [revision] for {447296a93c21c0e519d87fe5df16685c86d6334e}

- arch/x86/boot/compressed/tpm/tpm2_cmds.c
Use cpu_to_be32 for the message size for TPM2 extend
> [revision] for {f326a838319dd76255943b8a7008680382a8af6b}

- arch/x86/boot/compressed/sl_main.c
Fix include location for sha256.h
Not sure why these two headers are in different places...
> [revision] for {2ba13df24ceca280eec1e42a3fbdc60a1f3fc4c8}

- arch/x86/boot/compressed/tpm/tpm1_cmds.c
- arch/x86/boot/compressed/tpm/tpm2_cmds.c
- arch/x86/boot/compressed/tpm/tpm_buff.c
Adding guards for extend command to ensure buffer has been allocated
and adding the <string.h> missing include.
> revisions for early tpm code

- .gitignore
- .gitlab-ci.yml
- basic building
- NixOS package building
- store binary artifacts in the gitlab.com
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
> gitlab-ci.yml: add basic CI file

- arch/x86/boot/compressed/sl_stub.S
- arch/x86/boot/compressed/vmlinux.lds.S
The problem was the AP stacks were not being moved to the AP wake block.
The kernel was uncompressed in place so %esp for the APs pointed to memroy
within the uncompressed kernel.
> Fix long standing crash seen on Oracle servers

- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/asm-offsets.c
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
Add wake block size and check in early stub.
Also make sure TXT resets clear the secrets bits.
> Add wake block size

- arch/x86/boot/compressed/sl_main.c
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
Added a base and size field so the TPM event log can be allocated anywhere. Note this does not preclude it from still residing in the TXT heap if desired.
> Allow the TPM event log to reside anywhere

- drivers/iommu/intel-iommu.c
These commits prevent the kernel from TBOOT initiated panics if the DMAR is not fully parsed. Specifically it does not fail to start the IOMMU when RMRR values are found to be incorrect or inconsistent. These were cherry picked from 5.6. If the next rebase is on 5.6 these can be ignored.
> IOMMU fixes

- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
This closes up all the holes where we don't want the MLE to use these regions.
> Use memblock_reserve to reserve TXT regions and PMR hole

- arch/x86/Kconfig
- arch/x86/kernel/reboot.c
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
- kernel/kexec_core.c
The commit "reboot: Secure Launch SEXIT support on reboot paths" will go out as a separate patch. During the rebase, it should be right after the "kexec: Secure Launch kexec SEXIT support" commit.
Note the PR has a minor unrelated commit for removing AMD refs from Kconfig
> SEXIT on reboot paths

- arch/x86/boot/compressed/head_64.S
- arch/x86/boot/compressed/sl_stub.S
- include/linux/slaunch.h
Note the commit against 447296a93c21c0e519d87fe5df16685c86d6334e will probably have some conflicts with the AMD patch
> Switch to using %ebx for the base pointer to the kernel image

- arch/x86/boot/compressed/sl_stub.S
Remove extra push %ebx. It was already pushed by the Intel check
above.
> [revision] for {4588fa415fa1b713bd0d669d91cd62aafc29cbe2}

- arch/x86/boot/compressed/early_sha256.c
- lib/crypto/sha256.c
With newer GCC packages, the exports in the sha256.c code cause
problem in the PIE compressed kernel. This conditionally removes
the exporting.
> [revision] for {31ce1a54f39520f54fa7e1b4df9263ea035a1816}

- arch/x86/kernel/slaunch.c
- arch/x86/kernel/smpboot.c
- drivers/char/tpm/tpm-chip.c
Fix testing of SL_FLAGS when determining if SL is TXT and active.
> Fix testing of SL_FLAGS when determining if SL is TXT and active

- arch/x86/Kconfig
- arch/x86/boot/compressed/sl_main.c
- include/linux/slaunch.h
Use of PCRs 19 and 20 can be set independently via Kconfig.
> Allow use of alternate PCR 19 and 20 for post ACM measurements

- arch/x86/boot/compressed/sl_main.c
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
Ensure that the event log container size is less than or equal to the overall event log allocatd buffer.
> Validate the event log container size

- arch/x86/boot/compressed/head_64.S
- arch/x86/boot/compressed/sl_main.c
The compress kernel relocation and the decompression regions have to
be < 4GB and protected by the low PMR.
[set 6]
> Validate kernel relocation and decompression regions

- drivers/iommu/intel/iommu.c
- drivers/iommu/iommu.c
The IOMMU should always be set to default translated type after
the PMRs are disabled to protect the MLE from DMA.
This is a new patch should be placed after the tpm patch in the main patch set.
> iommu: Do not allow IOMMU passthrough with Secure Launch

- arch/x86/Kconfig
Add Kconfig constraints needed by Secure Launch
Force KASLR off; Secure Launch cannot interoperate with randomizing
the locations of things.
The AP wake code depends on x2apic support.
[set 7]
> Add Kconfig constraints needed by Secure Launch

- arch/x86/Kconfig
- arch/x86/boot/compressed/kaslr.c
- arch/x86/boot/compressed/sl_main.c
- drivers/iommu/intel/iommu.c
- drivers/iommu/iommu.c
- include/linux/slaunch.h
Instead of using compile time checks for disabling KASLR and preventing IOMMU passthrough mode, use runtime checks. This means these features can be available when the kernel is booted w/o secure launch.
> Runtime checks to disable certain features

- arch/x86/boot/compressed/kernel_info.S
- arch/x86/boot/compressed/sl_stub.S
With the PIE and relocation changes, %ebx no longer carries around
the base of the MLE but rather the entry point sl_stub_entry. Use
the MLE page tables passed in %ecx to find the MLE base.
> [revision] for {c6b66cb80abb08afd8719e4597fbbbd8943a6d2a}

- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/slaunch.c
Two Intel platform specific changes that missed the LKML cut
> Intel changes

- arch/x86/kernel/slaunch.c
Do not panic if TXT pub regs are unavailable, it just means TXT is disabled.
> No pub TXT registers

- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/setup.c
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
Using the feature bit instead of the vendor information was suggested by Andrew Cooper. It is a more precise way to determine if the platform supports secure launch.
> Use CPUID SMX feature bit

- arch/x86/boot/compressed/kaslr.c
- drivers/iommu/intel/iommu.c
- drivers/iommu/iommu.c
Per the comment from the LKML v2 post, adding special case disabling of features like IOMMU passthrough and KASLR is not going to go over well and is not good form. We can just avoid this via configuration and settings at runtime.
> No disabling special cases for Secure Launch

- arch/x86/kernel/e820.c
- arch/x86/kernel/kdebugfs.c
- arch/x86/kernel/ksysfs.c
- arch/x86/kernel/setup.c
- arch/x86/mm/ioremap.c
These two patches will end up at the beginning of our LKML v3 submission. The fix:
commit b3c72fc9a78e (x86/boot: Introduce setup_indirect)
> Fix original setup_indirect patch

- arch/x86/boot/compressed/sl_stub.S
Fix define for CPUID SMX feature bit.
> [revision] for {cae676ead103dbc385d27a6fdce0c4ff83b0083f}

- Documentation/x86/boot.rst
- arch/x86/boot/compressed/sl_main.c
- arch/x86/include/uapi/asm/bootparam.h
- arch/x86/kernel/slaunch.c
Use loadflags SLAUNCH_FLAG to communicate Secure Launch status from compressed kernel to kernel proper.
> SLAUNCH_FLAG loadflags bit

- Documentation/security/launch-integrity/principles.rst
- Documentation/security/launch-integrity/secure_launch_details.rst
- Documentation/security/launch-integrity/secure_launch_overview.rst
- arch/x86/boot/compressed/sl_main.c
Just whitespace issues in the code/docs.
Note the commit message for the SHA patch needs work:
ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit c4d5b9f ("crypto: sha1 - implement base layer for SHA-1")'
#12:
The SHA code here has its origins in the code from the main kernel, commit
c4d5b9f (crypto: sha1 - implement base layer for SHA-1). That code could
WARNING: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#13:
c4d5b9f (crypto: sha1 - implement base layer for SHA-1). That code could
> Cleanup from checkpatch.pl

- include/linux/slr_table.h
Add the bootloader context to the DL info structure.
> [revision] for {2347bd055b9c614999ee3b9974bc7f3dba098132}

- arch/x86/kernel/smpboot.c
Initialize ret = 0 since the Secure Launch SMP startup code does not set it.
> [revision] for {138f1b8aaafa8e80a3dd781df64b8cc04437a41f}
