TrenchBoot/linux

- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
- kernel/kexec_core.c
This PR is a bit different. The first two commits fix up files in the previous patch set. The last commit is a new patch for the series.
> SEXIT functionality

- arch/x86/boot/compressed/sl_main.c
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
These three commits cover adding support to write the TPM event log. This is done in the early secure launch stub code as it measures things like the command line before use. The ability to write the event log is also exposed via the securityfs module.
> TPM event logging functionality and securityfs interface

- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/asm-offsets.c
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
Added new TXT structs and cleaned up spacing in existing ones.
> Structure additions and cleanup

- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/asm-offsets.c
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
Also use asm-offsets for all TXT heap tables.
> Switch to using memremap on the TXT heap

- arch/x86/boot/compressed/sl_main.c
- arch/x86/kernel/slaunch.c
> Patch 6 review2 minor cleanup

- arch/x86/kernel/asm-offsets.c
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
Trying to get to a final layout for the OS-MLE struct
> Some adjustments to the OS-MLE structure in the TXT heap

- arch/x86/kernel/slaunch.c
Leave TXT heap mapped for the TPM 2.0 logging structure
> Leave TXT heap mapped for the TPM 2.0 logging structure

- arch/x86/boot/compressed/early_sha1.c
- arch/x86/boot/compressed/early_sha1.h
- arch/x86/boot/compressed/early_sha256.c
- arch/x86/boot/compressed/early_sha512.c
- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/boot/compressed/tpm/crb.c
- arch/x86/boot/compressed/tpm/crb.h
- arch/x86/boot/compressed/tpm/tis.c
- arch/x86/boot/compressed/tpm/tis.h
- arch/x86/boot/compressed/tpm/tpm.c
- arch/x86/boot/compressed/tpm/tpm.h
- arch/x86/boot/compressed/tpm/tpm1.h
- arch/x86/boot/compressed/tpm/tpm1_cmds.c
- arch/x86/boot/compressed/tpm/tpm2.h
- arch/x86/boot/compressed/tpm/tpm2_auth.c
- arch/x86/boot/compressed/tpm/tpm2_auth.h
- arch/x86/boot/compressed/tpm/tpm2_cmds.c
- arch/x86/boot/compressed/tpm/tpm2_constants.h
- arch/x86/boot/compressed/tpm/tpm_buff.c
- arch/x86/boot/compressed/tpm/tpm_common.h
- arch/x86/boot/compressed/tpm/tpmbuff.h
- arch/x86/boot/compressed/tpm/tpmio.c
- arch/x86/boot/compressed/vmlinux.lds.S
- arch/x86/kernel/slaunch.c
- include/linux/sha512.h
- include/linux/slaunch.h
- lib/sha512.c
> Fix copyright statements

- arch/x86/boot/compressed/kernel_info.S
- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/asm-offsets.c
- include/linux/slaunch.h
Changes from Daniel Kiper's review round 1.
> Changes from review round 1

- arch/x86/Kconfig
- arch/x86/boot/compressed/head_64.S
- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/slaunch.c
- include/linux/slaunch.h
hese are all the changes from the code review on 9/9 minus the TPM issues which are still being worked on.
> Miscellaneous minor fixes from final code review

- arch/x86/boot/compressed/tpm/crb.c
- arch/x86/boot/compressed/tpm/tis.c
- arch/x86/boot/compressed/tpm/tpm2.h
- arch/x86/boot/compressed/tpm/tpm2_auth.c
- arch/x86/boot/compressed/tpm/tpm_buff.c
Miscellaneous small fixes and cleanup to catchup with tpmlib
> Miscellaneous small fixes and cleanup to catchup with tpmlib

- arch/x86/boot/compressed/sl_main.c
- arch/x86/kernel/slaunch.c
- arch/x86/kernel/slmodule.c
- include/linux/slaunch.h
Related commits in preparation for the TPM extend change
> Misc fixes prior to main TPM extend change

- arch/x86/boot/compressed/kernel_info.S
- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/slaunch.c
- arch/x86/kernel/slmodule.c
- include/linux/slaunch.h
Commit comments indicate what was fixed/cleaned up.
> Miscellaneous set of minor fixes/cleanup

- arch/x86/boot/compressed/early_sha1.c
- arch/x86/boot/compressed/early_sha1.h
- arch/x86/boot/compressed/early_sha256.c
- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/slaunch.c
- arch/x86/kernel/slmodule.c
- include/linux/slaunch.h
> Update copyrights to 2021

- arch/x86/kernel/slaunch.c
- arch/x86/kernel/slmodule.c
Use sizeof var instead of sizeof type where it makes sense.
> Sizeof var

- arch/x86/boot/compressed/head_64.S
- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/slaunch.c
- arch/x86/kernel/smpboot.c
- include/linux/slaunch.h
Final misc. changes from internal review
> Final misc. changes from internal review

- arch/x86/boot/compressed/sl_main.c
Move setup_data handling to its own function and fix it to handle
setup_indirect entries.
> [revision] for {c6b66cb80abb08afd8719e4597fbbbd8943a6d2a}

- Documentation/x86/index.rst
- Documentation/x86/secure-launch.rst
Introduce background, overview and configuration/ABI information
for the Secure Launch kernel feature.
> Documentation/x86: Secure Launch kernel documentation

- Documentation/x86/secure-launch.rst
- arch/x86/kernel/kdebugfs.c
- arch/x86/kernel/slmodule.c
- drivers/char/tpm/tpm-chip.c
These are the 4 commits that will go into patches from the review. The other changes are in a couple of the commit messages/cover letter and will be fixed there.
> LKML version 4 posting changes

- Documentation/security/index.rst
- Documentation/security/launch-integrity/index.rst
- Documentation/security/launch-integrity/principles.rst
- Documentation/security/launch-integrity/secure_launch_details.rst
- Documentation/security/launch-integrity/secure_launch_overview.rst
- Documentation/x86/index.rst
Rework of the Secure Launch documentation.
> [revision] for {e0a50e780bbc}

- arch/x86/Kconfig
- arch/x86/boot/compressed/sl_main.c
- include/linux/slaunch.h
> Fix alternate PCR naming

- Documentation/security/launch-integrity/secure_launch_overview.rst
- arch/x86/boot/compressed/early_sha1.c
- arch/x86/kernel/slaunch.c
- arch/x86/kernel/smpboot.c
Miscellaneous set of changes from internal code review for v5 posting.
> Miscellaneous set of changes from internal code review

- Documentation/security/launch-integrity/principles.rst
> [revision] for {e0a50e780bbc0bb82fbdc28ceafa8ea8acbfe0c8}

- arch/x86/kernel/slmodule.c
addressing review comments on securityfs comments.
> [revision] for {7f34827cdf6628ed23fe4d152c211f5bef0d8060}

- arch/x86/Kconfig
- arch/x86/boot/compressed/sl_main.c
- arch/x86/boot/compressed/sl_stub.S
- arch/x86/kernel/asm-offsets.c
- arch/x86/kernel/slaunch.c
- arch/x86/kernel/slmodule.c
- include/linux/slaunch.h
- include/linux/slr_table.h
The SLR Table is the new interface between the pre and post launch code
> Switch to using SLR Table

- arch/x86/boot/compressed/sl_main.c
- drivers/firmware/efi/libstub/x86-stub.c
- include/linux/slr_table.h
Switch to using UEFI instead of EFI for definitions and structs.
> [revision] for {2347bd055b9c614999ee3b9974bc7f3dba098132}

- Documentation/security/launch-integrity/secure_launch_details.rst
- Documentation/security/launch-integrity/secure_launch_overview.rst
Fix up documentation with Secure Launch Specification and SLRT.
> [revision] for {f77b8f32cde35c601f1538b4413e3ad6842235f4}
